services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chess
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /code
        - action: rebuild
          path: ./backend/requirements.txt
          target: /code/requirements.txt
    env_file:
      - ./backend/.env.docker
    depends_on:
      - redis
      - postgres
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /code
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
          target: /code/package.json
    command: bun run dev --host
    restart: unless-stopped

volumes:
  postgres_data:
