services:
  redis:
    image: redis:8.0-M03-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /code
          ignore:
            - app.db
        - action: rebuild
          path: ./backend/requirements.txt
          target: /code/requirements.txt
    env_file:
      - ./backend/.env.docker
    depends_on:
      - redis
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /code
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
          target: /code/package.json
    command: bun run dev --host
    restart: unless-stopped
