services:
  redis:
    image: redis:8.0-M03-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env.docker
    depends_on:
      - redis
    command: sh -c "alembic upgrade head && fastapi dev --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bun run dev --host
    restart: unless-stopped
