"""game model changed for ai

Revision ID: fc80cde8ff12
Revises: 6c6903e4613f
Create Date: 2025-02-26 11:36:53.740903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc80cde8ff12'
down_revision: Union[str, None] = '6c6903e4613f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_type', sa.String(), nullable=True))
    op.add_column('games', sa.Column('ai_difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ai_difficulty')
    op.drop_column('games', 'game_type')
    # ### end Alembic commands ###
